site :opscode

cookbook 'apache2'
cookbook 'apt'
cookbook 'aws'
cookbook 'base',          :git => 'git@github.com:TheSerapher/chef-base.git'
cookbook 'build-essential'
cookbook 'chef-client'
cookbook 'cron'
cookbook 'database'
cookbook 'iptables'
cookbook 'mysql'
cookbook 'ntp'
cookbook 'openssh'
cookbook 'openssl'
cookbook 'perl'
cookbook 'php'
cookbook 'postgresql'
cookbook 'qmailtoaster',  :git => 'git@github.com:TheSerapher/chef-qmailtoaster.git'
cookbook 'selinux'
cookbook 'shorewall'
cookbook 'sudo'
cookbook 'suphp',         :git => 'git@github.com:TheSerapher/chef-suphp.git'
cookbook 'up2date',       :git => 'git@github.com:TheSerapher/chef-up2date.git'
cookbook 'users'
cookbook 'vsftpd'
cookbook 'xfs'
cookbook 'xml'
cookbook 'yum'
